---
- name: Install filebeat
  hosts: webservers
  become: yes

  tasks:
  - name: Download deb from artifacts.elastic.co
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.6.2-amd64.deb

  - name: install filebeat 
    command: dpkg -i filebeat-7.6.2-amd64.deb

  - name: copy config from ansible to web vms
    ansible.builtin.copy:
      src: /etc/ansible/files/filebeat-config.yml
      dest: /etc/filebeat/filebeat.yml

  - name: enable and configure system module
    command: filebeat modules enable system

  - name: filebeat setup
    command: filebeat setup

  - name: filebeat start
    command: service filebeat start

  - name: enable filebeat on boot
    ansible.builtin.systemd:
      name: filebeat
      state: started 
      enabled: yes

